# Generated by Django 4.0 on 2023-06-19 10:06

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email field')),
                ('dateOfBirth', models.DateField()),
                ('profileImg', models.ImageField(blank=True, upload_to='')),
                ('mobileNumber', models.CharField(default='Not Provided', max_length=10, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewId', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.FloatField()),
                ('comment', models.CharField(max_length=400)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airbnb_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseIds', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airbnb_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('houseId', models.BigAutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('nearestTown', models.CharField(max_length=200)),
                ('houseImgs', models.ImageField(blank=True, upload_to='')),
                ('pricePerDay', models.IntegerField()),
                ('bookingStart', models.DateTimeField()),
                ('bookingEnd', models.DateTimeField()),
                ('reviewId', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airbnb_app.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingId', models.BigAutoField(primary_key=True, serialize=False)),
                ('bookingStart', models.DateTimeField()),
                ('bookingEnd', models.DateTimeField()),
                ('numberOfAdults', models.IntegerField(default=0)),
                ('numberOfChild', models.IntegerField(default=0)),
                ('houseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airbnb_app.house')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airbnb_app.customer')),
            ],
        ),
    ]
