# Generated by Django 4.0 on 2023-06-20 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='houseImgs',
        ),
        migrations.CreateModel(
            name='HouseImg',
            fields=[
                ('imgId', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('houseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airbnb_app.house')),
            ],
        ),
    ]
