# Generated by Django 4.0 on 2023-06-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0002_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profileImg',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='house',
            name='houseImgs',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
