# Generated by Django 4.0 on 2023-06-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0003_house_aminities_house_country_house_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='bookingEnd',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='bookingStart',
            field=models.DateField(),
        ),
    ]
