# Generated by Django 4.0 on 2023-06-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0004_alter_house_bookingend_alter_house_bookingstart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='bookingEnd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='bookingStart',
            field=models.DateField(blank=True, null=True),
        ),
    ]
