# Generated by Django 4.0 on 2023-06-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0005_alter_house_bookingend_alter_house_bookingstart'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='houseImg',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
