# Generated by Django 4.0 on 2023-06-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0006_house_houseimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookingEnd',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bookingStart',
            field=models.DateField(),
        ),
    ]
